import { createInterface } from 'readline';
import { randomBytes } from 'crypto';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { homedir, platform, release, type as osType } from 'os';
import { join, resolve } from 'path';
import { execFileSync } from 'child_process';
import { KB_DIR, ENV_PATH } from '../paths.js';

const HOME = homedir();

function isNpx() {
  return !!(process.env.npm_execpath?.includes('npx') ||
    process.argv[1]?.includes('.npm/_npx') ||
    process.argv[1]?.includes('node_modules/.cache'));
}

// ---------------------------------------------------------------------------
// Utility helpers
// ---------------------------------------------------------------------------

function out(text) { process.stdout.write(text); }
function outln(text = '') { process.stdout.write(text + '\n'); }

function genHex(bytes = 32) { return randomBytes(bytes).toString('hex'); }
function genBase64(bytes = 32) { return randomBytes(bytes).toString('base64'); }

function which(cmd) {
  try {
    execFileSync('which', [cmd], { stdio: 'ignore' });
    return true;
  } catch { return false; }
}

function detectVaultPath() {
  const candidates = [
    join(HOME, 'obsidian-vault'),
    join(HOME, 'Documents', 'Obsidian'),
    join(HOME, 'Obsidian'),
  ];
  for (const p of candidates) {
    if (existsSync(p)) return p;
  }
  return null;
}

// ---------------------------------------------------------------------------
// Readline prompt helpers
// ---------------------------------------------------------------------------

function createRl() {
  return createInterface({ input: process.stdin, output: process.stdout });
}

function ask(rl, question, defaultVal = '') {
  const suffix = defaultVal ? ` [${defaultVal}]` : '';
  return new Promise(resolve => {
    rl.question(`  ${question}${suffix}: `, answer => {
      resolve(answer.trim() || defaultVal);
    });
  });
}

async function askChoice(rl, question, choices, defaultIdx = 0) {
  outln();
  choices.forEach((c, i) => {
    const marker = i === defaultIdx ? '>' : ' ';
    outln(`  ${marker} ${i + 1}) ${c}`);
  });
  const answer = await ask(rl, question, String(defaultIdx + 1));
  const idx = parseInt(answer, 10) - 1;
  if (idx >= 0 && idx < choices.length) return idx;
  return defaultIdx;
}

async function askMulti(rl, question, choices) {
  outln();
  choices.forEach((c, i) => {
    outln(`    ${i + 1}) ${c}`);
  });
  outln(`    A) All`);
  const answer = await ask(rl, question, 'A');
  if (answer.toUpperCase() === 'A') return choices.map((_, i) => i);
  return answer.split(/[,\s]+/).map(s => parseInt(s, 10) - 1).filter(i => i >= 0 && i < choices.length);
}

// ---------------------------------------------------------------------------
// Environment detection
// ---------------------------------------------------------------------------

function detectEnvironment() {
  const env = {
    os: `${osType()} ${platform()} ${release()}`,
    nodeVersion: process.version,
    tools: {},
  };

  const toolMap = {
    claude: 'Claude Code',
    codex: 'OpenAI Codex CLI',
    gemini: 'Google Gemini CLI',
    ollama: 'Ollama',
  };

  for (const [cmd, label] of Object.entries(toolMap)) {
    env.tools[cmd] = { label, available: which(cmd) };
  }

  return env;
}

// ---------------------------------------------------------------------------
// Config generation
// ---------------------------------------------------------------------------

function buildEnvContent(cfg) {
  const lines = [
    '# Knowledge Base Server Configuration',
    `# Generated by setup wizard on ${new Date().toISOString()}`,
    '',
    '# Server port for the dashboard',
    `KB_PORT=${cfg.port}`,
    '',
    '# Dashboard login password',
    `KB_PASSWORD=${cfg.password}`,
    '',
    '# Obsidian vault path (leave empty if not using Obsidian)',
    `OBSIDIAN_VAULT_PATH=${cfg.vaultPath || ''}`,
    '',
  ];

  // API keys per agent
  if (cfg.agents && cfg.agents.length > 0) {
    lines.push('# Brain API keys — one per AI agent');
    for (const agent of cfg.agents) {
      const envName = `KB_API_KEY_${agent.toUpperCase()}`;
      const key = cfg.apiKeys?.[agent] || genHex();
      lines.push(`${envName}=${key}`);
    }
    lines.push('');
  }

  // Auth secret
  lines.push('# Better Auth secret (for OAuth / remote Brain API)');
  lines.push(`BETTER_AUTH_SECRET=${cfg.authSecret || genBase64()}`);
  lines.push('');

  if (cfg.brainApi) {
    lines.push('# Brain API public URL');
    lines.push(`BETTER_AUTH_URL=https://${cfg.brainDomain}`);
    lines.push('');
  }

  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Service installation helpers
// ---------------------------------------------------------------------------

function installSystemd() {
  // Resolve kb binary path — use the actual resolved path, not just 'kb',
  // because systemd PATH may not include npm bin directories
  let kbBin;
  try {
    kbBin = execFileSync('which', ['kb'], { encoding: 'utf-8' }).trim();
  } catch {
    kbBin = 'kb'; // fallback — user will need to fix PATH in unit
  }
  const unit = `[Unit]
Description=Knowledge Base Server
After=network.target

[Service]
Type=simple
User=${process.env.USER || 'root'}
WorkingDirectory=${HOME}
ExecStart=${kbBin} start
Restart=on-failure
RestartSec=5
Environment=NODE_ENV=production

[Install]
WantedBy=multi-user.target
`;
  const unitPath = '/etc/systemd/system/knowledge-base.service';
  try {
    writeFileSync(unitPath, unit);
    execFileSync('systemctl', ['daemon-reload'], { stdio: 'ignore' });
    execFileSync('systemctl', ['enable', 'knowledge-base'], { stdio: 'ignore' });
    return { ok: true, path: unitPath };
  } catch (err) {
    return { ok: false, error: err.message, content: unit };
  }
}

function installLaunchd() {
  let kbBin;
  try {
    kbBin = execFileSync('which', ['kb'], { encoding: 'utf-8' }).trim();
  } catch {
    kbBin = '/usr/local/bin/kb';
  }
  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.knowledgebase.server</string>
  <key>ProgramArguments</key>
  <array>
    <string>${kbBin}</string>
    <string>start</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${HOME}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
</dict>
</plist>
`;
  const plistPath = join(HOME, 'Library', 'LaunchAgents', 'com.knowledgebase.server.plist');
  try {
    mkdirSync(join(HOME, 'Library', 'LaunchAgents'), { recursive: true });
    writeFileSync(plistPath, plist);
    return { ok: true, path: plistPath };
  } catch (err) {
    return { ok: false, error: err.message, content: plist };
  }
}

function generateDockerCompose(cfg) {
  const content = `version: "3.8"
services:
  knowledge-base:
    image: node:22-slim
    command: ["npx", "knowledge-base-server", "start"]
    ports:
      - "${cfg.port}:${cfg.port}"
    volumes:
      - kb-data:/root/.knowledge-base
${cfg.vaultPath ? `      - ${cfg.vaultPath}:/vault` : ''}
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  kb-data:
`;
  const composePath = join(KB_DIR, 'docker-compose.yml');
  writeFileSync(composePath, content);
  return composePath;
}

// ---------------------------------------------------------------------------
// MCP registration per agent
// ---------------------------------------------------------------------------

function registerMcpClaude() {
  const claudeJsonPath = join(HOME, '.claude.json');
  let config = {};
  if (existsSync(claudeJsonPath)) {
    try { config = JSON.parse(readFileSync(claudeJsonPath, 'utf-8')); } catch { config = {}; }
  }
  if (!config.mcpServers) config.mcpServers = {};
  config.mcpServers['knowledge-base'] = { command: 'kb', args: ['mcp'] };
  writeFileSync(claudeJsonPath, JSON.stringify(config, null, 2));
  return claudeJsonPath;
}

function registerMcpCodex() {
  const dir = join(HOME, '.codex');
  mkdirSync(dir, { recursive: true });
  const mcpPath = join(dir, 'mcp.json');
  let config = {};
  if (existsSync(mcpPath)) {
    try { config = JSON.parse(readFileSync(mcpPath, 'utf-8')); } catch { config = {}; }
  }
  if (!config.mcpServers) config.mcpServers = {};
  config.mcpServers['knowledge-base'] = { command: 'kb', args: ['mcp'] };
  writeFileSync(mcpPath, JSON.stringify(config, null, 2));
  return mcpPath;
}

function registerMcpGemini() {
  const dir = join(HOME, '.gemini');
  mkdirSync(dir, { recursive: true });
  const mcpPath = join(dir, 'mcp.json');
  let config = {};
  if (existsSync(mcpPath)) {
    try { config = JSON.parse(readFileSync(mcpPath, 'utf-8')); } catch { config = {}; }
  }
  if (!config.mcpServers) config.mcpServers = {};
  config.mcpServers['knowledge-base'] = { command: 'kb', args: ['mcp'] };
  writeFileSync(mcpPath, JSON.stringify(config, null, 2));
  return mcpPath;
}

const MCP_REGISTRARS = {
  claude: registerMcpClaude,
  codex: registerMcpCodex,
  gemini: registerMcpGemini,
};

// ---------------------------------------------------------------------------
// Parse --auto CLI flags
// ---------------------------------------------------------------------------

function parseAutoArgs(args) {
  const cfg = {};
  for (const arg of args) {
    const m = arg.match(/^--(\w[\w-]*)=(.*)$/);
    if (m) {
      const [, key, val] = m;
      if (key === 'port') cfg.port = parseInt(val, 10);
      else if (key === 'password') cfg.password = val;
      else if (key === 'vault') cfg.vaultPath = val === 'none' ? '' : resolve(val.replace(/^~/, HOME));
      else if (key === 'agents') cfg.agents = val.split(',').map(s => s.trim().toLowerCase());
      else if (key === 'deploy') cfg.deploy = val;
      else if (key === 'brain') cfg.brainApi = val === 'true' || val === 'yes';
      else if (key === 'domain') cfg.brainDomain = val;
    }
  }
  return cfg;
}

function loadConfigFile() {
  const configPath = join(KB_DIR, 'setup-config.json');
  if (!existsSync(configPath)) return null;
  try {
    return JSON.parse(readFileSync(configPath, 'utf-8'));
  } catch { return null; }
}

// ---------------------------------------------------------------------------
// Interactive wizard
// ---------------------------------------------------------------------------

async function runInteractive(env) {
  const rl = createRl();
  const cfg = {};

  // 1. Welcome
  outln();
  outln('========================================');
  outln('  Knowledge Base Server Setup');
  outln('========================================');
  outln();

  // 2. Environment
  outln('  Detected environment:');
  outln(`    OS:   ${env.os}`);
  outln(`    Node: ${env.nodeVersion}`);
  outln(`    AI tools found:`);
  for (const [, info] of Object.entries(env.tools)) {
    outln(`      ${info.available ? '[x]' : '[ ]'} ${info.label}`);
  }
  outln();

  // 3. Dashboard password
  const randomPw = genHex(8);
  outln('  Dashboard password protects the web UI.');
  outln('  Press Enter to generate a random one, or type your own.');
  cfg.password = await ask(rl, 'Dashboard password', randomPw);

  // 4. Server port
  outln();
  outln('  The dashboard and API will listen on this port.');
  const portStr = await ask(rl, 'Server port', '3838');
  cfg.port = parseInt(portStr, 10) || 3838;

  // 5. Obsidian vault
  outln();
  outln('  If you use Obsidian, the vault will be indexed for search.');
  const detected = detectVaultPath();
  const vaultDefault = detected || 'none';
  if (detected) {
    outln(`  Auto-detected vault: ${detected}`);
  }
  outln('  Enter a path, or "none" to skip Obsidian integration.');
  const vaultAnswer = await ask(rl, 'Obsidian vault path', vaultDefault);
  cfg.vaultPath = vaultAnswer === 'none' ? '' : resolve(vaultAnswer.replace(/^~/, HOME));

  // 6. AI agents
  outln();
  outln('  Select which AI agents will connect to the knowledge base.');
  outln('  Each gets a unique API key for authentication.');
  const agentChoices = ['Claude Code', 'OpenAI Codex', 'Google Gemini', 'Ollama'];
  const agentKeys = ['claude', 'codex', 'gemini', 'ollama'];
  const selected = await askMulti(rl, 'Select agents (comma-separated numbers, or A for all)', agentChoices);
  cfg.agents = selected.map(i => agentKeys[i]);
  cfg.apiKeys = {};
  for (const agent of cfg.agents) {
    cfg.apiKeys[agent] = genHex();
  }

  // 7. Deployment mode
  const deployChoices = [];
  const deployKeys = [];
  if (platform() === 'linux') { deployChoices.push('systemd (auto-start on boot)'); deployKeys.push('systemd'); }
  if (platform() === 'darwin') { deployChoices.push('launchd (auto-start on boot)'); deployKeys.push('launchd'); }
  deployChoices.push('Docker (docker-compose)');
  deployKeys.push('docker');
  deployChoices.push('PM2 (process manager)');
  deployKeys.push('pm2');
  deployChoices.push('Manual (run kb start yourself)');
  deployKeys.push('manual');

  outln();
  outln('  How should the server run?');
  const deployIdx = await askChoice(rl, 'Deployment mode', deployChoices, 0);
  cfg.deploy = deployKeys[deployIdx];

  // 8. Brain API
  outln();
  outln('  The Brain API allows remote HTTPS access from AI agents.');
  outln('  Requires a domain name and reverse proxy (e.g., Caddy, nginx).');
  const brainAnswer = await ask(rl, 'Enable Brain API? (y/N)', 'n');
  cfg.brainApi = brainAnswer.toLowerCase().startsWith('y');
  if (cfg.brainApi) {
    cfg.brainDomain = await ask(rl, 'Domain for Brain API', 'brain.yourdomain.com');
  }

  cfg.authSecret = genBase64();

  rl.close();
  return cfg;
}

// ---------------------------------------------------------------------------
// Apply configuration
// ---------------------------------------------------------------------------

function applyConfig(cfg) {
  const results = { steps: [] };

  // 1. Write .env
  const envContent = buildEnvContent(cfg);
  const envPath = ENV_PATH;
  const envExisted = existsSync(envPath);
  writeFileSync(envPath, envContent);
  results.steps.push({
    action: envExisted ? 'Updated .env' : 'Created .env',
    path: envPath,
  });

  // 2. Register MCP for each agent that has a registrar
  for (const agent of (cfg.agents || [])) {
    if (MCP_REGISTRARS[agent]) {
      try {
        const path = MCP_REGISTRARS[agent]();
        results.steps.push({ action: `Registered MCP for ${agent}`, path });
      } catch (err) {
        results.steps.push({ action: `Failed to register MCP for ${agent}`, error: err.message });
      }
    }
  }

  // 3. Install service
  // Warn npx users about persistent service limitations
  if (isNpx() && cfg.deploy !== 'manual' && cfg.deploy !== 'docker') {
    results.steps.push({
      action: 'Warning: npx detected',
      hint: 'Persistent services (systemd/launchd/PM2) require a global install: npm i -g knowledge-base-server. The npx cache is ephemeral.',
    });
  }

  if (cfg.deploy === 'systemd') {
    const r = installSystemd();
    if (r.ok) {
      results.steps.push({ action: 'Installed systemd service', path: r.path });
    } else {
      results.steps.push({
        action: 'Could not install systemd service (may need sudo)',
        error: r.error,
        hint: 'Save the unit file manually and run: sudo systemctl daemon-reload && sudo systemctl enable knowledge-base',
      });
    }
  } else if (cfg.deploy === 'launchd') {
    const r = installLaunchd();
    if (r.ok) {
      results.steps.push({ action: 'Installed launchd plist', path: r.path });
    } else {
      results.steps.push({ action: 'Could not install launchd plist', error: r.error });
    }
  } else if (cfg.deploy === 'docker') {
    const path = generateDockerCompose(cfg);
    results.steps.push({ action: 'Generated docker-compose.yml', path });
  } else if (cfg.deploy === 'pm2') {
    results.steps.push({
      action: 'PM2 selected',
      hint: 'Run: pm2 start $(which kb) --name knowledge-base -- start',
    });
  }

  // 4. First ingest if vault provided
  if (cfg.vaultPath && existsSync(cfg.vaultPath)) {
    results.ingestPath = cfg.vaultPath;
  }

  results.cfg = cfg;
  return results;
}

// ---------------------------------------------------------------------------
// Print summary
// ---------------------------------------------------------------------------

function printSummary(results) {
  outln();
  outln('========================================');
  outln('  Setup Complete');
  outln('========================================');
  outln();

  for (const step of results.steps) {
    outln(`  [done] ${step.action}`);
    if (step.path) outln(`         ${step.path}`);
    if (step.hint) outln(`         ${step.hint}`);
    if (step.error) outln(`         Error: ${step.error}`);
  }

  const cfg = results.cfg;
  outln();
  outln('  SENSITIVE — do not share or log the following values:');
  outln('  Configuration summary:');
  outln(`    Port:      ${cfg.port}`);
  outln(`    Password:  ${cfg.password}`);
  outln(`    Vault:     ${cfg.vaultPath || '(none)'}`);
  outln(`    Agents:    ${(cfg.agents || []).join(', ') || '(none)'}`);
  outln(`    Deploy:    ${cfg.deploy || 'manual'}`);
  if (cfg.brainApi) {
    outln(`    Brain API: https://${cfg.brainDomain}`);
  }

  if (cfg.apiKeys && Object.keys(cfg.apiKeys).length > 0) {
    outln();
    outln('  SENSITIVE — do not share or log the following values:');
    outln('  API keys (save these — they are not stored elsewhere):');
    for (const [agent, key] of Object.entries(cfg.apiKeys)) {
      outln(`    ${agent}: ${key}`);
    }
  }

  outln();
  outln('  Next steps:');
  outln('    1. Review .env and adjust if needed');
  if (results.ingestPath) {
    outln(`    2. Run: kb ingest ${results.ingestPath}`);
    outln('    3. Run: kb start');
  } else {
    outln('    2. Run: kb start');
  }
  outln(`    Dashboard: http://localhost:${cfg.port}`);
  outln();
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

export async function setup(args = []) {
  const isAuto = args.includes('--auto');

  const env = detectEnvironment();

  if (isAuto) {
    // Agent mode: combine config file + CLI flags, no prompts
    const fileConfig = loadConfigFile() || {};
    const cliConfig = parseAutoArgs(args);
    const merged = { ...fileConfig, ...cliConfig };

    // Apply defaults for anything not specified
    const cfg = {
      port: merged.port || 3838,
      password: merged.password || genHex(8),
      vaultPath: merged.vaultPath !== undefined ? merged.vaultPath : (detectVaultPath() || ''),
      agents: merged.agents || Object.keys(env.tools).filter(k => env.tools[k].available),
      deploy: merged.deploy || 'manual',
      brainApi: merged.brainApi || false,
      brainDomain: merged.brainDomain || 'brain.yourdomain.com',
      authSecret: merged.authSecret || genBase64(),
      apiKeys: {},
    };

    // Generate API keys for each agent
    for (const agent of cfg.agents) {
      cfg.apiKeys[agent] = merged.apiKeys?.[agent] || genHex();
    }

    outln('Knowledge Base Server — automatic setup');
    outln();

    const results = applyConfig(cfg);
    printSummary(results);
    return;
  }

  // Interactive mode
  const cfg = await runInteractive(env);
  const results = applyConfig(cfg);
  printSummary(results);
}
